### ISSUE TITLE
Wrong @2x Conversion

### ISSUE THREAD

**Issue by onursenture** [terwanerik/Retini#2] opened 2015-11-10 16:19 UTC
@2x outputs are bigger than @3x input file. Ex: I drop a 1125x80 pixel image with @3x suffix, Retini gives me a 1500x117 pixel @2x output.

**Comment by terwanerik** [comment] 2015-11-10 16:41
Is it 72dpi or something else? I recently found a bug where 300dpi jpeg images weren't resized correctly, was going to look into that.

**Comment by onursenture** [comment] 2015-11-10 16:43
Its 72 dpi png. https://www.dropbox.com/s/66yco5a8ywx24ir/Screenshot%202015-11-10%2018.42.56.png?dl=0

**Comment by terwanerik** [comment] 2015-11-10 16:43
Alright thanks! I'm going to look into that.

**Comment by onursenture** [comment] 2015-11-10 16:57
By the way @2x outputs are exactly double sized of the correct resolution.

**Comment by terwanerik** [comment] 2015-11-14 15:01
Is there a way you can send the actual image this is happening with? I generated the exact same image (in size, dpi etc.) in PS, but it's resizing as it should.

**Comment by onursenture** [comment] 2015-11-15 01:40
Sure. It might be related with my workflow because all the images I have been working on converted wrong. 

![switch_soundon 3x](https://cloud.githubusercontent.com/assets/244957/11166709/7bcf94e0-8b4a-11e5-9cc0-03fd984e6630.png)
![button_oyna 3x](https://cloud.githubusercontent.com/assets/244957/11166711/80ba8f96-8b4a-11e5-9d8a-037d017fda0e.png)
![button_ayarlar 3x](https://cloud.githubusercontent.com/assets/244957/11166713/83cfff4a-8b4a-11e5-9a33-1e149e456969.png)

**Comment by onursenture** [comment] 2015-11-15 01:41
These files has @3x postfix by the way.

**Comment by terwanerik** [comment] 2015-11-17 16:50
Alright, i tried 'm all, and they all resize just fine. I think when you uploaded it to the image server the server converted it to a proper PNG. Are you sure it's an actual PNG? Or a jpeg/tiff/psd with a PNG extension?

**Comment by onursenture** [comment] 2015-11-17 19:17
Nop, I'm pretty sure that these are all proper pngs.

**Comment by terwanerik** [comment] 2015-11-20 16:55
You mentioned that it might be because of your workflow, what is your workflow if i may aks? I still am unable to reproduce the problem.

**Comment by terwanerik** [comment] 2015-12-11 16:39
Are you using a retina Mac? I just bought a retina MacBook, and noticed some weird problems. Going to look into this asap.

**Comment by onursenture** [comment] 2015-12-11 17:02
Yes! I’m using retina Macbook.

**Comment by terwanerik** [comment] 2015-12-22 21:42
Fixed this in version 1.0.8. Closing.

**Closed as completed** 2015-12-22 21:42 UTC

**Comment by onursenture** [comment] 2015-12-23 14:49
Thanks! I'll try asap.

**Comment by terwanerik** [comment] 2016-01-13 20:21
Just to be sure, it's working for you as well?

**Comment by onursenture** [comment] 2016-01-13 21:08
I haven’t yet updated. We have started a project with buggy version, I’ll update Retini after we release the project. :)

Onur Şentüre / Product Designer 
onur@orkestrayazilim.com / 05355021052

Orkestra Yazılım 
R. Oğuz Arık Mah. Bestekar Sok. 62/8Çankaya, Ankara 
http://orkestra.co
